### Create a channel
POST http://localhost:3000/api/channels
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2QwNWM3ZjczODdiNjc3NzkyYzFjZGYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDQxMDM4MDgsImV4cCI6MTc0NDE5MDIwOH0.p__NYNif5r9N1BbqbMMN1Bm2OfloLsjqtwYqzDaVXAI

{
    "name": "nameChannel3"
}