### Delete user by ID
PUT {{baseUrl}}/users/67d05c497387b677792c1cde/approve
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2QwNWM3ZjczODdiNjc3NzkyYzFjZGYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDE3MDg0OTQsImV4cCI6MTc0MTc5NDg5NH0.t0DpIUXEkD5HrTASKXm2xmnmcScA9fkzYQ_aP0DDbbU